//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd/branche_Rose/chat.proto
namespace chat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_ChannleChat_CS")]
  public partial class MSG_Req_ChannleChat_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_ChannleChat_CS() {}
    

    private string _str_chat = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"str_chat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string str_chat
    {
      get { return _str_chat; }
      set { _str_chat = value; }
    }

    private string _src_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"src_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string src_name
    {
      get { return _src_name; }
      set { _src_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_ChannelChat_SC")]
  public partial class MSG_Ret_ChannelChat_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_ChannelChat_SC() {}
    

    private string _str_chat = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"str_chat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string str_chat
    {
      get { return _str_chat; }
      set { _str_chat = value; }
    }

    private string _src_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"src_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string src_name
    {
      get { return _src_name; }
      set { _src_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}