//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gamemap.proto
namespace map
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMapFileHeader")]
  public partial class GameMapFileHeader : global::ProtoBuf.IExtensible
  {
    public GameMapFileHeader() {}
    
    private uint _magic = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint magic
    {
      get { return _magic; }
      set { _magic = value; }
    }
    private uint _ver = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ver
    {
      get { return _ver; }
      set { _ver = value; }
    }
    private uint _width = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint width
    {
      get { return _width; }
      set { _width = value; }
    }
    private uint _height = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint height
    {
      get { return _height; }
      set { _height = value; }
    }
    private uint _real_width = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"real_width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint real_width
    {
      get { return _real_width; }
      set { _real_width = value; }
    }
    private uint _real_height = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"real_height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint real_height
    {
      get { return _real_height; }
      set { _real_height = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewTile")]
  public partial class NewTile : global::ProtoBuf.IExtensible
  {
    public NewTile() {}
    
    private uint _flags = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMapFile")]
  public partial class GameMapFile : global::ProtoBuf.IExtensible
  {
    public GameMapFile() {}
    
    private map.GameMapFileHeader _fileHeader = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fileHeader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public map.GameMapFileHeader fileHeader
    {
      get { return _fileHeader; }
      set { _fileHeader = value; }
    }
    private readonly global::System.Collections.Generic.List<map.NewTile> _tiles = new global::System.Collections.Generic.List<map.NewTile>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tiles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<map.NewTile> tiles
    {
      get { return _tiles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TileFlag")]
    public enum TileFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TILE_BLOCK_NORMAL", Value=1)]
      TILE_BLOCK_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TILE_BLOCK_MAGIC", Value=2)]
      TILE_BLOCK_MAGIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TILE_BLOCK_ENTRY", Value=4)]
      TILE_BLOCK_ENTRY = 4
    }
  
}