//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd/branche_Rose/magic_msg.proto
namespace magic
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillData")]
  public partial class SkillData : global::ProtoBuf.IExtensible
  {
    public SkillData() {}
    

    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private ulong _lastusetime = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastusetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong lastusetime
    {
      get { return _lastusetime; }
      set { _lastusetime = value; }
    }

    private uint _playtime = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint playtime
    {
      get { return _playtime; }
      set { _playtime = value; }
    }

    private uint _qlevel = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"qlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint qlevel
    {
      get { return _qlevel; }
      set { _qlevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_MagicAttack_CS")]
  public partial class MSG_Req_MagicAttack_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_MagicAttack_CS() {}
    

    private ulong _targetid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }

    private uint _targettype = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targettype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targettype
    {
      get { return _targettype; }
      set { _targettype = value; }
    }

    private uint _magictype = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"magictype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint magictype
    {
      get { return _magictype; }
      set { _magictype = value; }
    }

    private uint _desx = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desx
    {
      get { return _desx; }
      set { _desx = value; }
    }

    private uint _desy = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desy
    {
      get { return _desy; }
      set { _desy = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_StartMagicAttack_SC")]
  public partial class MSG_Ret_StartMagicAttack_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_StartMagicAttack_SC() {}
    

    private ulong _att_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"att_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong att_tempid
    {
      get { return _att_tempid; }
      set { _att_tempid = value; }
    }

    private uint _desx = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"desx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desx
    {
      get { return _desx; }
      set { _desx = value; }
    }

    private uint _desy = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desy
    {
      get { return _desy; }
      set { _desy = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PKResult")]
  public partial class PKResult : global::ProtoBuf.IExtensible
  {
    public PKResult() {}
    

    private ulong _def_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"def_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong def_tempid
    {
      get { return _def_tempid; }
      set { _def_tempid = value; }
    }

    private uint _def_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"def_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint def_type
    {
      get { return _def_type; }
      set { _def_type = value; }
    }

    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }

    private int _changehp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"changehp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int changehp
    {
      get { return _changehp; }
      set { _changehp = value; }
    }

    private uint _retcode = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MagicAttack_SC")]
  public partial class MSG_Ret_MagicAttack_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MagicAttack_SC() {}
    

    private ulong _att_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"att_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong att_tempid
    {
      get { return _att_tempid; }
      set { _att_tempid = value; }
    }

    private ulong _def_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"def_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong def_tempid
    {
      get { return _def_tempid; }
      set { _def_tempid = value; }
    }

    private uint _desx = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desx
    {
      get { return _desx; }
      set { _desx = value; }
    }

    private uint _desy = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desy
    {
      get { return _desy; }
      set { _desy = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private readonly global::System.Collections.Generic.List<magic.PKResult> _pklist = new global::System.Collections.Generic.List<magic.PKResult>();
    [global::ProtoBuf.ProtoMember(7, Name=@"pklist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<magic.PKResult> pklist
    {
      get { return _pklist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_HpMpPop_SC")]
  public partial class MSG_Ret_HpMpPop_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_HpMpPop_SC() {}
    

    private ulong _tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }

    private uint _entry_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"entry_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint entry_type
    {
      get { return _entry_type; }
      set { _entry_type = value; }
    }

    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }

    private int _hp_change = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp_change", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp_change
    {
      get { return _hp_change; }
      set { _hp_change = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_SyncSkillStage_CS")]
  public partial class MSG_Req_SyncSkillStage_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_SyncSkillStage_CS() {}
    

    private ulong _targetid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }

    private uint _targettype = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targettype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targettype
    {
      get { return _targettype; }
      set { _targettype = value; }
    }

    private uint _skillstage = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillstage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillstage
    {
      get { return _skillstage; }
      set { _skillstage = value; }
    }

    private uint _desx = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desx
    {
      get { return _desx; }
      set { _desx = value; }
    }

    private uint _desy = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desy
    {
      get { return _desy; }
      set { _desy = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_SyncSkillStage_SC")]
  public partial class MSG_Ret_SyncSkillStage_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_SyncSkillStage_SC() {}
    

    private ulong _att_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"att_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong att_tempid
    {
      get { return _att_tempid; }
      set { _att_tempid = value; }
    }

    private uint _att_type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"att_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint att_type
    {
      get { return _att_type; }
      set { _att_type = value; }
    }

    private ulong _def_tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"def_tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong def_tempid
    {
      get { return _def_tempid; }
      set { _def_tempid = value; }
    }

    private uint _def_type = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"def_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint def_type
    {
      get { return _def_type; }
      set { _def_type = value; }
    }

    private uint _skillstage = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillstage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillstage
    {
      get { return _skillstage; }
      set { _skillstage = value; }
    }

    private uint _desx = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"desx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desx
    {
      get { return _desx; }
      set { _desx = value; }
    }

    private uint _desy = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"desy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desy
    {
      get { return _desy; }
      set { _desy = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MainUserDeath_SC")]
  public partial class MSG_Ret_MainUserDeath_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MainUserDeath_SC() {}
    

    private ulong _tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }

    private uint _waittime = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"waittime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint waittime
    {
      get { return _waittime; }
      set { _waittime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_MainUserRelive_CS")]
  public partial class MSG_Req_MainUserRelive_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_MainUserRelive_CS() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MainUserRelive_SC")]
  public partial class MSG_Ret_MainUserRelive_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MainUserRelive_SC() {}
    

    private ulong _userid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong userid
    {
      get { return _userid; }
      set { _userid = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}