//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd/branche_Rose/message.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterBaseData")]
  public partial class CharacterBaseData : global::ProtoBuf.IExtensible
  {
    public CharacterBaseData() {}
    

    private ulong _exp = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }

    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private uint _tilizhi = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tilizhi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tilizhi
    {
      get { return _tilizhi; }
      set { _tilizhi = value; }
    }

    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _famelevel = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"famelevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint famelevel
    {
      get { return _famelevel; }
      set { _famelevel = value; }
    }

    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }

    private uint _viplevel = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"viplevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint viplevel
    {
      get { return _viplevel; }
      set { _viplevel = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }

    private uint _laststage = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"laststage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint laststage
    {
      get { return _laststage; }
      set { _laststage = value; }
    }

    private ulong _nextexp = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"nextexp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong nextexp
    {
      get { return _nextexp; }
      set { _nextexp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttributeData")]
  public partial class AttributeData : global::ProtoBuf.IExtensible
  {
    public AttributeData() {}
    

    private uint _power = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint power
    {
      get { return _power; }
      set { _power = value; }
    }

    private uint _matt = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"matt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint matt
    {
      get { return _matt; }
      set { _matt = value; }
    }

    private uint _patt = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"patt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint patt
    {
      get { return _patt; }
      set { _patt = value; }
    }

    private uint _mdef = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mdef
    {
      get { return _mdef; }
      set { _mdef = value; }
    }

    private uint _pdef = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pdef
    {
      get { return _pdef; }
      set { _pdef = value; }
    }

    private uint _parry = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"parry", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint parry
    {
      get { return _parry; }
      set { _parry = value; }
    }

    private uint _hit = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hit
    {
      get { return _hit; }
      set { _hit = value; }
    }

    private uint _toughness = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"toughness", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint toughness
    {
      get { return _toughness; }
      set { _toughness = value; }
    }

    private uint _crit = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint crit
    {
      get { return _crit; }
      set { _crit = value; }
    }

    private uint _attackspeed = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"attackspeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attackspeed
    {
      get { return _attackspeed; }
      set { _attackspeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterMainData")]
  public partial class CharacterMainData : global::ProtoBuf.IExtensible
  {
    public CharacterMainData() {}
    

    private msg.CharacterBaseData _basedata = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"basedata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterBaseData basedata
    {
      get { return _basedata; }
      set { _basedata = value; }
    }

    private msg.AttributeData _attridata = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attridata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.AttributeData attridata
    {
      get { return _attridata; }
      set { _attridata = value; }
    }

    private msg.MapUserData _mapdata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.MapUserData mapdata
    {
      get { return _mapdata; }
      set { _mapdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterMapShow")]
  public partial class CharacterMapShow : global::ProtoBuf.IExtensible
  {
    public CharacterMapShow() {}
    

    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }

    private uint _weapon = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"weapon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weapon
    {
      get { return _weapon; }
      set { _weapon = value; }
    }

    private uint _coat = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint coat
    {
      get { return _coat; }
      set { _coat = value; }
    }

    private uint _occupation = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint occupation
    {
      get { return _occupation; }
      set { _occupation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterMapData")]
  public partial class CharacterMapData : global::ProtoBuf.IExtensible
  {
    public CharacterMapData() {}
    

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _movespeed = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"movespeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint movespeed
    {
      get { return _movespeed; }
      set { _movespeed = value; }
    }

    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }

    private uint _maxhp = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _state = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> state
    {
      get { return _state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapUserData")]
  public partial class MapUserData : global::ProtoBuf.IExtensible
  {
    public MapUserData() {}
    

    private ulong _charid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private msg.CharacterMapShow _mapshow = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mapshow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterMapShow mapshow
    {
      get { return _mapshow; }
      set { _mapshow = value; }
    }

    private msg.CharacterMapData _mapdata = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterMapData mapdata
    {
      get { return _mapdata; }
      set { _mapdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapNpcData")]
  public partial class MapNpcData : global::ProtoBuf.IExtensible
  {
    public MapNpcData() {}
    

    private ulong _baseid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }

    private ulong _tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }

    private uint _maxhp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }

    private uint _movespeed = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"movespeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint movespeed
    {
      get { return _movespeed; }
      set { _movespeed = value; }
    }

    private uint _attspeed = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"attspeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attspeed
    {
      get { return _attspeed; }
      set { _attspeed = value; }
    }

    private string _master_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"master_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string master_name
    {
      get { return _master_name; }
      set { _master_name = value; }
    }

    private uint _visit = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"visit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint visit
    {
      get { return _visit; }
      set { _visit = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _state = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> state
    {
      get { return _state; }
    }
  

    private msg.CharacterMapShow _showdata = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"showdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterMapShow showdata
    {
      get { return _showdata; }
      set { _showdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Create_Role_CS")]
  public partial class MSG_Create_Role_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Create_Role_CS() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _occupation = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint occupation
    {
      get { return _occupation; }
      set { _occupation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_DataCharacterMain_SC")]
  public partial class MSG_DataCharacterMain_SC : global::ProtoBuf.IExtensible
  {
    public MSG_DataCharacterMain_SC() {}
    

    private msg.CharacterMainData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterMainData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Use_GM_CS")]
  public partial class MSG_Req_Use_GM_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Use_GM_CS() {}
    

    private string _strcontent = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strcontent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strcontent
    {
      get { return _strcontent; }
      set { _strcontent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Common_Error_SC")]
  public partial class MSG_Ret_Common_Error_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Common_Error_SC() {}
    

    private uint _errorcode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Common_Tips_SC")]
  public partial class MSG_Ret_Common_Tips_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Common_Tips_SC() {}
    

    private string _strcontent = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strcontent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strcontent
    {
      get { return _strcontent; }
      set { _strcontent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Main_Data_CS")]
  public partial class MSG_Req_Main_Data_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Main_Data_CS() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Base_Item_CS")]
  public partial class MSG_Req_Base_Item_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Base_Item_CS() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Base_Item_SC")]
  public partial class MSG_Ret_Base_Item_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Base_Item_SC() {}
    

    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }

    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Stage_Info_CS")]
  public partial class MSG_Req_Stage_Info_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Stage_Info_CS() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageInfo")]
  public partial class StageInfo : global::ProtoBuf.IExtensible
  {
    public StageInfo() {}
    

    private uint _stageid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stageid
    {
      get { return _stageid; }
      set { _stageid = value; }
    }

    private uint _star = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }

    private uint _leftTimes = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leftTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint leftTimes
    {
      get { return _leftTimes; }
      set { _leftTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Stage_Info_SC")]
  public partial class MSG_Ret_Stage_Info_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Stage_Info_SC() {}
    
    private readonly global::System.Collections.Generic.List<msg.StageInfo> _stages = new global::System.Collections.Generic.List<msg.StageInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.StageInfo> stages
    {
      get { return _stages; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Enter_Stage_CS")]
  public partial class MSG_Req_Enter_Stage_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Enter_Stage_CS() {}
    

    private uint _stageid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stageid
    {
      get { return _stageid; }
      set { _stageid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stageDropInfo")]
  public partial class stageDropInfo : global::ProtoBuf.IExtensible
  {
    public stageDropInfo() {}
    

    private uint _itemid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }

    private uint _itemnum = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemnum
    {
      get { return _itemnum; }
      set { _itemnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Enter_Stage_SC")]
  public partial class MSG_Ret_Enter_Stage_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Enter_Stage_SC() {}
    

    private uint _errorcode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.stageDropInfo> _drops = new global::System.Collections.Generic.List<msg.stageDropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"drops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.stageDropInfo> drops
    {
      get { return _drops; }
    }
  

    private uint _uhitnum = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uhitnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uhitnum
    {
      get { return _uhitnum; }
      set { _uhitnum = value; }
    }

    private uint _ucritnum = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ucritnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ucritnum
    {
      get { return _ucritnum; }
      set { _ucritnum = value; }
    }

    private uint _sthitnum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sthitnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sthitnum
    {
      get { return _sthitnum; }
      set { _sthitnum = value; }
    }

    private uint _stcritnum = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stcritnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stcritnum
    {
      get { return _stcritnum; }
      set { _stcritnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Finish_Stage_CS")]
  public partial class MSG_Req_Finish_Stage_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Finish_Stage_CS() {}
    

    private uint _starnum = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"starnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint starnum
    {
      get { return _starnum; }
      set { _starnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Finish_Stage_SC")]
  public partial class MSG_Ret_Finish_Stage_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Finish_Stage_SC() {}
    

    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private msg.CharacterBaseData _basedata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"basedata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.CharacterBaseData basedata
    {
      get { return _basedata; }
      set { _basedata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Test_Network_CS")]
  public partial class MSG_Req_Test_Network_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Test_Network_CS() {}
    

    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _num2 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"num2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> num2
    {
      get { return _num2; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_GameTime_SC")]
  public partial class MSG_Ret_GameTime_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_GameTime_SC() {}
    

    private ulong _gametime = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gametime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong gametime
    {
      get { return _gametime; }
      set { _gametime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_UserGameTime_SC")]
  public partial class MSG_Req_UserGameTime_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Req_UserGameTime_SC() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_UserGameTime_CS")]
  public partial class MSG_Ret_UserGameTime_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_UserGameTime_CS() {}
    

    private uint _usertempid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"usertempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint usertempid
    {
      get { return _usertempid; }
      set { _usertempid = value; }
    }

    private ulong _gametime = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gametime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong gametime
    {
      get { return _gametime; }
      set { _gametime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_NotifyUserKickout_SC")]
  public partial class MSG_Ret_NotifyUserKickout_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_NotifyUserKickout_SC() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_ServerLoginFailed_SC")]
  public partial class MSG_Ret_ServerLoginFailed_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_ServerLoginFailed_SC() {}
    

    private uint _returncode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"returncode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint returncode
    {
      get { return _returncode; }
      set { _returncode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_UserMapInfo_SC")]
  public partial class MSG_Ret_UserMapInfo_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_UserMapInfo_SC() {}
    

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private string _mapname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mapname
    {
      get { return _mapname; }
      set { _mapname = value; }
    }

    private string _filename = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_NineScreenRefreshPlayer_SC")]
  public partial class MSG_Ret_NineScreenRefreshPlayer_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_NineScreenRefreshPlayer_SC() {}
    
    private readonly global::System.Collections.Generic.List<msg.MapUserData> _data = new global::System.Collections.Generic.List<msg.MapUserData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.MapUserData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenRefreshCharacter_SC")]
  public partial class MSG_Ret_MapScreenRefreshCharacter_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenRefreshCharacter_SC() {}
    

    private msg.MapUserData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.MapUserData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenRemoveCharacter_SC")]
  public partial class MSG_Ret_MapScreenRemoveCharacter_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenRemoveCharacter_SC() {}
    

    private ulong _charid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenBatchRemoveCharacter_SC")]
  public partial class MSG_Ret_MapScreenBatchRemoveCharacter_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenBatchRemoveCharacter_SC() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _charids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"charids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> charids
    {
      get { return _charids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveData")]
  public partial class MoveData : global::ProtoBuf.IExtensible
  {
    public MoveData() {}
    

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Req_Move_CS")]
  public partial class MSG_Req_Move_CS : global::ProtoBuf.IExtensible
  {
    public MSG_Req_Move_CS() {}
    

    private ulong _charid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.MoveData> _movedata = new global::System.Collections.Generic.List<msg.MoveData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"movedata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.MoveData> movedata
    {
      get { return _movedata; }
    }
  

    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_Move_SC")]
  public partial class MSG_Ret_Move_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_Move_SC() {}
    

    private ulong _charid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong charid
    {
      get { return _charid; }
      set { _charid = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.MoveData> _movedata = new global::System.Collections.Generic.List<msg.MoveData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"movedata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.MoveData> movedata
    {
      get { return _movedata; }
    }
  

    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_SetState_SC")]
  public partial class MSG_Ret_SetState_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_SetState_SC() {}
    

    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_ClearState_SC")]
  public partial class MSG_Ret_ClearState_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_ClearState_SC() {}
    

    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }

    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenBatchRefreshNpc_SC")]
  public partial class MSG_Ret_MapScreenBatchRefreshNpc_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenBatchRefreshNpc_SC() {}
    
    private readonly global::System.Collections.Generic.List<msg.MapNpcData> _data = new global::System.Collections.Generic.List<msg.MapNpcData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.MapNpcData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenBatchRemoveNpc_SC")]
  public partial class MSG_Ret_MapScreenBatchRemoveNpc_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenBatchRemoveNpc_SC() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _tempids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tempids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> tempids
    {
      get { return _tempids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenRefreshNpc_SC")]
  public partial class MSG_Ret_MapScreenRefreshNpc_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenRefreshNpc_SC() {}
    

    private msg.MapNpcData _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg.MapNpcData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenRemoveNpc_SC")]
  public partial class MSG_Ret_MapScreenRemoveNpc_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenRemoveNpc_SC() {}
    

    private ulong _tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FuncNpcData")]
  public partial class FuncNpcData : global::ProtoBuf.IExtensible
  {
    public FuncNpcData() {}
    

    private ulong _baseid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"baseid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong baseid
    {
      get { return _baseid; }
      set { _baseid = value; }
    }

    private ulong _tempid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MSG_Ret_MapScreenFuncNpc_SC")]
  public partial class MSG_Ret_MapScreenFuncNpc_SC : global::ProtoBuf.IExtensible
  {
    public MSG_Ret_MapScreenFuncNpc_SC() {}
    
    private readonly global::System.Collections.Generic.List<msg.FuncNpcData> _data = new global::System.Collections.Generic.List<msg.FuncNpcData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.FuncNpcData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}