//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Cmd/branche_Rose/msg_enum.proto
namespace msg
{
    [global::ProtoBuf.ProtoContract(Name=@"MapDataType")]
    public enum MapDataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP_DATATYPE_USER", Value=0)]
      MAP_DATATYPE_USER = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP_DATATYPE_NPC", Value=1)]
      MAP_DATATYPE_NPC = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UserCharbaseState")]
    public enum UserCharbaseState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARBASE_OK", Value=1)]
      CHARBASE_OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARBASE_FORBID", Value=2)]
      CHARBASE_FORBID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHARBASE_FORBID_NAME", Value=4)]
      CHARBASE_FORBID_NAME = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginRetCode")]
    public enum LoginRetCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_UNKNOWN", Value=0)]
      LOGIN_RETURN_UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_VERSIONERROR", Value=1)]
      LOGIN_RETURN_VERSIONERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_UUID", Value=2)]
      LOGIN_RETURN_UUID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_DB", Value=3)]
      LOGIN_RETURN_DB = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_PASSWORDERROR", Value=4)]
      LOGIN_RETURN_PASSWORDERROR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_CHANGEPASSWORD", Value=5)]
      LOGIN_RETURN_CHANGEPASSWORD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_IDINUSE", Value=6)]
      LOGIN_RETURN_IDINUSE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_IDINCLOSE", Value=7)]
      LOGIN_RETURN_IDINCLOSE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_GATEWAYNOTAVAILABLE", Value=8)]
      LOGIN_RETURN_GATEWAYNOTAVAILABLE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_USERMAX", Value=9)]
      LOGIN_RETURN_USERMAX = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_ACCOUNTEXIST", Value=10)]
      LOGIN_RETURN_ACCOUNTEXIST = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_ACCOUNTSUCCESS", Value=11)]
      LOGIN_RETURN_ACCOUNTSUCCESS = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_CHARNAMEREPEAT", Value=12)]
      LOGIN_RETURN_CHARNAMEREPEAT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_USERDATANOEXIST", Value=13)]
      LOGIN_RETURN_USERDATANOEXIST = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_USERNAMEREPEAT", Value=14)]
      LOGIN_RETURN_USERNAMEREPEAT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TIMEOUT", Value=15)]
      LOGIN_RETURN_TIMEOUT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_PAYFAILED", Value=16)]
      LOGIN_RETURN_PAYFAILED = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_JPEG_PASSPORT", Value=17)]
      LOGIN_RETURN_JPEG_PASSPORT = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_LOCK", Value=18)]
      LOGIN_RETURN_LOCK = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_WAITACTIVE", Value=19)]
      LOGIN_RETURN_WAITACTIVE = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_NEWUSER_OLDZONE", Value=20)]
      LOGIN_RETURN_NEWUSER_OLDZONE = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_UUID_ERROR", Value=21)]
      LOGIN_RETURN_UUID_ERROR = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_USER_TOZONE", Value=22)]
      LOGIN_RETURN_USER_TOZONE = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_CHANGE_LOGIN", Value=23)]
      LOGIN_RETURN_CHANGE_LOGIN = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_MATRIX_ERROR", Value=24)]
      LOGIN_RETURN_MATRIX_ERROR = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_MATRIX_NEED", Value=25)]
      LOGIN_RETURN_MATRIX_NEED = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_MATRIX_LOCK", Value=26)]
      LOGIN_RETURN_MATRIX_LOCK = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_MATRIX_DOWN", Value=27)]
      LOGIN_RETURN_MATRIX_DOWN = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_OLDUSER_NEWZONE", Value=28)]
      LOGIN_RETURN_OLDUSER_NEWZONE = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_IMG_LOCK", Value=29)]
      LOGIN_RETURN_IMG_LOCK = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_PASSPOD_PASSWORDERROR", Value=30)]
      LOGIN_RETURN_PASSPOD_PASSWORDERROR = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_PASSPOD_DOWN", Value=31)]
      LOGIN_RETURN_PASSPOD_DOWN = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_BUSY", Value=32)]
      LOGIN_RETURN_BUSY = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_FORBID", Value=33)]
      LOGIN_RETURN_FORBID = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_IMG_LOCK2", Value=34)]
      LOGIN_RETURN_IMG_LOCK2 = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_MAINTAIN", Value=35)]
      LOGIN_RETURN_MAINTAIN = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TDCODE_GEN_ERROR", Value=36)]
      LOGIN_RETURN_TDCODE_GEN_ERROR = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TDCODE_DOWN", Value=37)]
      LOGIN_RETURN_TDCODE_DOWN = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TOKEN_ERROR", Value=38)]
      LOGIN_RETURN_TOKEN_ERROR = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TOKEN_TOO_QUICK", Value=39)]
      LOGIN_RETURN_TOKEN_TOO_QUICK = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_TOKEN_TIMEOUT", Value=40)]
      LOGIN_RETURN_TOKEN_TIMEOUT = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_SHOW_MSG", Value=41)]
      LOGIN_RETURN_SHOW_MSG = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_USERINLOGIN", Value=42)]
      LOGIN_RETURN_USERINLOGIN = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RETURN_CHARNAME_INVALID", Value=43)]
      LOGIN_RETURN_CHARNAME_INVALID = 43
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Occupation")]
    public enum Occupation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Occu_Dema", Value=1)]
      Occu_Dema = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Occu_Yaohu", Value=2)]
      Occu_Yaohu = 2
    }
  
}