using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Net;
using System.Text;

/// 定义物品格子类型
public enum enumCellType
{
	OBJECTCELLTYPE_NONE,		/// 不是格子，用于丢弃或捡到物品
	OBJECTCELLTYPE_COMMON,		/// 普通物品格子
	OBJECTCELLTYPE_EQUIP,		/// 装备
	OBJECTCELLTYPE_MOUSE,		/// 鼠标
	OBJECTCELLTYPE_TRADE,		/// 自己的交易格子
	OBJECTCELLTYPE_OTHERTRADE,	/// 对方的交易格子
	OBJECTCELLTYPE_BANK,		/// 银行
	OBJECTCELLTYPE_SELL,		/// 卖
	OBJECTCELLTYPE_STORE,		/// 仓库
	OBJECTCELLTYPE_EQUIPSHOW,	/// 非自己穿着的装备
	OBJECTCELLTYPE_PACKAGE,		/// 包裹的格子
	OBJECTCELLTYPE_MAKE,		/// 合成、升级，镶嵌的格子
	OBJECTCELLTYPE_MYSHOP,		/// 自己摊位的格子
	OBJECTCELLTYPE_OTHERSSHOP,	/// 别的万家摊位的格子
	OBJECTCELLTYPE_MAIL,		/// 邮件系统的格子
	OBJECTCELLTYPE_COUNTRY_SAVEBOX, /// 国家倉库
	OBJECTCELLTYPE_PET,			/// 宠物包裹
	OBJECTCELLTYPE_GIFTBOX,     //宝盒的格子
	OBJECTCELLTYPE_GOD_EQUIP,	// 神器格子
	OBJECTCELLTYPE_RENT_STORE,      //租借的仓库
	OBJECTCELLTYPE_STONE = 20,		//改造千年寒铁
	OBJECTCELLTYPE_LIBAOBOX = 21,	//礼包宝箱
	OBJECTCELLTYPE_XIULIAN = 22,	//装备修炼紫装
	OBJECTCELLTYPE_NEWBOX = 23,		//新宝箱的物品格子
	OBJECTCELLTYPE_GOUHUO = 24,		//篝火鉴定酒

	OBJECTCELLTYPE_ITEMIDENTI = 240,	//鉴定
	OBJECTCELLTYPE_10STARENCOURAGE = 241,	//十星鼓励案
	OBJECTCELLTYPE_MAPIDENTI = 242,		//探险地图鉴定
	OBJECTCELLTYPE_RETURNFOOD_BOX= 243,	  //识别食物的格子
	OBJECTCELLTYPE_FEEDFOOD_BOX = 244,   //家族boss喂食
	OBJECTCELLTYPE_YAJINFU = 246,		//大师赛
	OBJECTCELLTYPE_NUMBERONE = 247,  //天下第一国压注
	OBJECTCELLTYPE_FABAO    = 248,  //法宝用格子
	OBJECTCELLTYPE_CONTRUCT = 249,   //建设大赛格子
	OBJECTCELLTYPE_EXP   = 250,     /// 功勋压注
	OBJECTCELLTYPE_KEY = 251, /// 放宝合钥匙
	OBJECTCELLTYPE_FURNITURONEOFF = 252, /// 一次性家具
	OBJECTCELLTYPE_HOMEPET   = 253,     /// 宠物喂养
	OBJECTCELLTYPE_FURNITURE = 254,     /// 家具仓库包裹


	OBJECTCELLTYPE_SET_EQUIP = 255,			// 一键装备设置	
	OBJECTCELLTYPE_TIANMA_EQUIP = 256,		// 天马合成格子
	OBJECTCELLTYPE_XUANLINMA_EQUIP = 257,	// 玄麟马合成格子
	OBJECTCELLTYPE_MODIFY_EQUIP = 258,		// 新改造格子
	OBJECTCELLTYPE_FEEDBABY_BOX = 259,	/// 喂养小孩的格子
	OBJECTCELLTYPE_CANGBAOTU = 260,			//藏宝图鉴定
	OBJECTCELLTYPE_UNIONRESOURCEPRIZE = 261,//资源收集任务帮会仓库
	OBJECTCELLTYPE_COMMON_TABLE = 262,		//通用的类似喂养小孩的格子
	OBJECTCELLTYPE_ADVHEROEQUIP_TABLE = 263,//英雄装备进阶的格子
	OBJECTCELLTYPE_SEPTTRAININGSTONE_TABLE = 264,	///家族修炼石修炼的格子
	OBJECTCELLTYPE_PUTINANDUSEITEM_TABLE = 265,		//放入道具并使用的通用格子，
	OBJECTCELLTYPE_HEROEQUIPMENT_TABLE = 266,		//放英雄装备的格子，
	OBJECTCELLTYPE_TRADBRAND_TABLE = 267,		//放圣者令的格子，
	OBJECTCELLTYPE_TRADEQUIPMENT_TABLE = 268,		//放圣者装备的格子，
	OBJECTCELLTYPE_SINGLE_COMMON_TABLE = 269,        //通用的单个格子的道具table
	OBJECTCELLTYPE_FETCH_AWARD =270,          //领取打地鼠奖励的道具格子
	OBJECTCELLTYPE_LIBAO_TABLE = 271,          //每月大礼包开启后物品NPC处寄存的格子
	OBJECTCELLTYPE_DRAGON = 272,				///龙宝宝存放包裹
	OBJECTCELLTYPE_COMMANBAG = 273,              //通用寄存包裹
	OBJECTCELLTYPE_PIONTTOBUY = 274, // 积分换购
	OBJECTCELLTYPE_ACTIVEPOINTPOOL = 275, //活跃度聚宝盆
	OBJECTCELLTYPE_LIBAONEW = 278,    //新礼包格子
	OBJECTCELLTYPE_SEPTWAR_PIONT_EXHANGE = 279,//家族豪门战功点数兑换
	OBJECTCELLTYPE_ONOFFLINE = 280,  //在线离线挖宝 可获得道具奖励
	OBJECTCELLTYPE_ONOFFLINE_REWARD = 281, //挖宝 获得道具
	OBJECTCELLTYPE_CONSUMEBACKLIST = 282,	//消费免单

	OBJECTCELLTYPE_UPDATESTARINSURANCE = 283,	//升星保险
};

public class MainModule : LSingleton<MainModule>
{
    public UI_MainWindow uiMainWindow;
    public MainNetWork CNetWork;
    public void Initialize()
    {
        uiMainWindow = new UI_MainWindow();
        uiMainWindow.Init();

        CNetWork = new MainNetWork();
        CNetWork.Initialize();
    }
}
